### ISSUE TITLE
Easier npm import

### ISSUE THREAD

**Issue by MartinJHammer** [redux-utilities/reduce-reducers#11]
Normally, at least in VS Code, I can import something by clicking ```ctrl + .```

This does not work with reduce-reducers. Instead  I have to manually write
```javascript
import * as reduceReducers from 'reduce-reducers';
```
If possible, make it so clicking ```ctrl + . ``` on reduceReducers() automatically adds the import
```javascript
import { reduceReducers } from 'reduce-reducers';
```

Thanks for this great utility function :)

**Comment by alvis** [comment]
The cause of the problem from babel-plugin-add-module-exports, as it adds `module.exports = exports['default']` in the transpiled code, effectively removing the default export. It also causes a problem in typescript because the definition expects a default export which is non-existent in the compiled code.

**Comment by timche** [comment]
So if `module.exports` is available, it will break `exports.default`? Because default `import`s work by importing `exports.default` and it's defined: https://unpkg.com/reduce-reducers@0.2.0/dist/index.js

**Comment by timche** [comment]
I'm open to release a new version with `export default` only, but it will be a breaking change which means it will be released as major version `2.0.0` and you need to upgrade manually.

**Comment by alvis** [comment]
They're (techniqually) mutually exclusive. A detailed explaination can be found here: https://stackoverflow.com/questions/40294870/module-exports-vs-export-default-in-node-js-and-es6 and http://2ality.com/2015/12/babel-commonjs.html.

In fact, the plugin is not very recommended by babel since we're invitably moving towards ES6. See https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/

Having said that, practically we can hack and make two export types working together as follow:
```
export default function reduce (...reducers){
  return (previous, current, ...args) =>
  reducers.reduce((p, r) => r(p, current, ...args), previous)
}

reduce.default = reduce;
```

**Comment by timche** [comment]
I just joined this repo recently and refactored a little and kept it like it is. I would suggest we publish different builds (ES module, CommonJS and UMD) as version `2.0.0`. How about that?

**Comment by timche** [comment]
@alvis please take a look at #12. I think that's how we should publish this library.

**Comment by timche** [comment]
I've published version `0.3.0` which includes an ES build now. Hope this also fixes your issue @MartinJHammer

**Comment by MartinJHammer** [comment]
I'll check it first thing tomorrow @timche . And thanks a bunch to you and the other fellows for the effort!

**Comment by MartinJHammer** [comment]
I tried it out, and it unfortunately doesn't work as expected.

My import is like below, and give no editor errors. I still cannot import it with `ctrl+.`
`import { reduceReducers } from 'reduce-reducers';`

Usage (var names change due to project being private):
```
export const appReducer = combineReducers({
    todos: reduceReducers(
        todoReducer,
        notifsReducer
    )
});
```
I get the following error in the console: `Uncaught TypeError: reduce_reducers_1.reduceReducers is not a function`

`import * as reduceReducers from 'reduce-reducers';` import also gives me same error now.

If it helps, I use reduceReducers with Angular 5.2.10 and angular-redux 7.1.1.

Thanks as always :)

**Comment by timche** [comment]
Have you tried `import reduceReducers from 'reduce-reducers';`?

**Comment by MartinJHammer** [comment]
@timche That works. Funny the other import type doesn't... Guess I have some reading up to do :P

**Comment by timche** [comment]
We are using [`export default`](https://github.com/redux-utilities/reduce-reducers/blob/master/src/index.js#L1), so it needs to be imported as default. There is no named export, so `import { foo } ` doesn't work at all.

If you are not too familiar with it, it's nicely explained here: https://stackoverflow.com/questions/36795819/when-should-i-use-curly-braces-for-es6-import/36796281#36796281

**Comment by MartinJHammer** [comment]
@timche Just finished reading the link, and it was way more enlightening that I had imagined. Thanks for taking your time to fulfill the issue and making me wiser.

Happy coding! :D

**Comment by patrixd** [comment]
I'm still having this issue but in a slightly different way.
I have some unit tests in mocha that works with the next import:
```
import * as reduceReducers from 'reduce-reducers';
```
But the webpack application that runs the same code does not work with that import, I get this error `Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_1_reduce_reducers__ is not a function`


Although the webpack app works with:
```
import reduceReducers from 'reduce-reducers';
```
Which does not work for the unit tests. I get this error : `TypeError: reduce_reducers_1.default is not a function`

Is there a way I can use the same code and works for both?

**Comment by mmalek06** [comment]
@patrixd have you found a solution to it? I have the exact same problem :(

**Comment by oleg-mtr** [comment]
I also have this problem: webpack build works, tests compilation fails with "default is not a function"

**Comment by oleg-mtr** [comment]
I also have this problem: webpack build works, tests compilation fails with "default is not a function"

In similar situations _(there are other modules with this problem)_, I use this ugly fix:

```js
// tslint:disable-next-line:no-var-requires
let reduceReducers = require("reduce-reducers");
if ("default" in reduceReducers) {
  reduceReducers = reduceReducers.default;
}
```

**Comment by SET001** [comment]
this problem may be avoided if not using default export which is considered to be harmful -
https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html
